AllCops:
  Exclude:
    - bin/*
    - config.ru
    - db/schema.rb

  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'included']
Style/Documentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
