AllCops:
  Exclude:
    - bin/*
    - config.ru
    - db/schema.rb

Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'included']
Style/Documentation:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
