version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/user-login-generator-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
