#!/bin/bash
if docker-compose exec -T api echo "Running in existing api container ..." 2>/dev/null
then
  run_or_exec="exec"
else
  run_or_exec="run --rm"
fi

docker-compose $run_or_exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" api bash -c "$*"
